apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
    ver: v1
  name: web-canary-v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
      ver: v1
  template:
    metadata:
      labels:
        app: web
        ver: v1
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        ports:
        - containerPort: 80
        volumeMounts:
          - name: config-nginx
            mountPath: /etc/nginx/conf.d
      volumes:
        - name: config-nginx
          configMap:
            name: nginx-configmap-v1
---
apiVersion: v1
data:
  default.conf: |-
    server {
        listen 80 default_server;
        server_name _;
        default_type text/plain;

        location / {
            return 200 '$hostname\n NORMAL application\n';
        }
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: nginx-configmap-v1

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: web
    ver: v1
  name: web-canary-v1-svc
spec:
  type: ClusterIP
  selector:
    app: web
    ver: v1
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80